name: "Build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'

env:
  LANG: en_US.UTF-8
jobs:
  build:
    name: JVM Tests - JDK ${{matrix.java.name}}
    runs-on: ${{ matrix.java.os-name }}
    strategy:
      fail-fast: false
      matrix:
        java:
          - {
            name: "11 Eclipse Temurin",
            java-version: 11,
            os-name: "ubuntu-latest",
            java-vendor: "temurin"
          }
          - {
            name: "17 Eclipse Temurin",
            java-version: 17,
            os-name: "ubuntu-latest",
            java-vendor: "temurin"}
          - {
            name: "11 Eclipse Zulu OpenJDK",
            java-version: 11,
            os-name: "ubuntu-latest",
            java-vendor: "zulu"
          }
          - {
            name: "17 Eclipse Zulu OpenJDK",
            java-version: 17,
            os-name: "ubuntu-latest",
            java-vendor: "zulu" }
          - {
            name: "11 Eclipse Temurin Windows",
            java-version: 11,
            os-name: "windows-latest",
            java-vendor: "temurin"
          }
    steps:
      - uses: actions/checkout@v2
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-repo-jdk-${{ matrix.java }}-${{ steps.get-date.outputs.date }}
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.java.java-vendor }}
          java-version: ${{ matrix.java.java-version }}
      - name: Build with Maven
        run: mvn -B clean install -Dno-format
      - name: Delete Local Artifacts From Cache
        shell: bash
        run: rm -rf ~/.m2/repository/io/quarkus/quarkus-fs-util*
